data=open("data.txt","w")
data.write("Hello how are you?")
data.close()
print("Data wriiten sucessfully")
print("**********************************")
data=open("data.txt","r")
print(data.read())
data.close()
print("**********************************")
print("Data read sucessfully")
data=open("data.txt","a")
data.write("\n I am fine")
data.close()
print("**************************************")
data=open("data.txt","r")
print(data.read())
data.close()
print("**********************************")
print("Data read sucessfully")
data=open("data1.txt","w+")
data.write("Good morning")
data.tell()
data.seek(0)
print(data.read())
print("*********************************************")

