s="My name is janvi"
print(len(s))
print(s.upper())
print(s.lower())
print(s.title())
print(s.capitalize())
print(s.find("name"))
print(s.count("name"))
print(s.endswith("vi"))
print(s.isalnum())
print("Janvi123".isalnum())
print(s.index("n"))
print(s.isalpha())
print("janvi".isalpha())
print(s.isdigit())
print("123".isdigit())
print(s.center(20,"*"))
print(s.center(40,"*"))
print(s.count("a"))
print(s.startswith("My"))
print(s.isspace())
print(" ".isspace())
print("123 ".isdigit())
print(s.replace("janvi","Nirja"))
